apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: casadocodigo-ingress
  namespace: casadocodigo-dev
  labels:
    app: casadocodigo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: casadocodigo.io.k8s.ic.unicamp.br
    http:
      paths:
      - backend:
          serviceName: casadocodigo-service
          servicePort: 8080
  tls:
  - hosts:
    - casadocodigo.io.k8s.ic.unicamp.br
    - cdc.mecsys.com.br
    secretName: casadocodigo-crt
---
kind: Service
apiVersion: v1
metadata:
  name: casadocodigo-service
  namespace: casadocodigo-dev
spec:
  selector:
    app: casadocodigo-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casadocodigo-app
  namespace: casadocodigo-dev
  labels:
    app: casadocodigo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casadocodigo-app
  template:
    metadata:
      labels:
        app: casadocodigo-app
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: casadocodigo
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
