stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: |-
        mvn clean package
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: casadocodigo:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34136
- name: Deploy
  steps:
  - applyYamlConfig:
      path: .deployment.yaml
timeout: 60
